# Generated by Django 2.1.8 on 2019-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cashflow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='est',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingAgent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingOffice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
